server:
  port: 8190

user:
  name: dev Abinash
  password : dev abinash
  xyz:
   abc: dev random value
   
notification:
   text:
      message: hello dev text from yaml places
      from: 20000000
   email:
      message: hello email from chh dev
      from: dev@gmail.com
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client_int_db
    username: root
    password: rootroot     
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
   
   