server:
  port: 8190

user:
  name: local Abinash
  password : local abinash
  xyz:
   abc: local random value
   
notification:
   text:
      message: hello text from yaml places local
      from: 100000000
   email:
      message: hello email from chh local
      from: local@gmail.com
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client_int_db
    username: root
    password: rootroot     
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
   
   